### ISSUE TITLE
Hi, i get error for make

### ISSUE THREAD

**Issue by VenusKanami** [rahvaalgatus/rahvaalgatus#301]
./node_modules/.bin/node-sass --recursive --indent-type tab --indent-width 1 --output-style expanded --output public/assets assets
fs.js:961
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/venus/rahvaalgatus/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at Object.getInstalledBinaries (/home/venus/rahvaalgatus/node_modules/node-sass/lib/extensions.js:130:13)
    at foundBinariesList (/home/venus/rahvaalgatus/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/venus/rahvaalgatus/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/venus/rahvaalgatus/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/venus/rahvaalgatus/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/venus/rahvaalgatus/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
Makefile:81: recipe for target 'stylesheets' failed
make: *** [stylesheets] Error 1

**Comment by moll** [comment]
Hey,

You could try reinstalling `node-sass` perhaps, but overall you've got to figure out why `./node_modules/.bin/node-sass` doesn't work. Are you using Node v6 or something newer? Maybe that's the issue?

**Comment by VenusKanami** [comment]
node -v
v6.17.1

**Comment by VenusKanami** [comment]
i try make make autocompile
make -j2 autojavascripts autostylesheets
make[1]: Entering directory '/home/venus/rahvaalgatus'
make -C app autocompile
./node_modules/.bin/node-sass --recursive --indent-type tab --indent-width 1 --output-style expanded --output public/assets assets
make[2]: Entering directory '/home/venus/rahvaalgatus/app'
make[3]: Entering directory '/home/venus/rahvaalgatus/app'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
mkdir -p ../tmp
Compiling public/assets/hwcrypto.js…
Compiling public/assets/inputs.js…
Compiling public/assets/editor.js…
Compiling public/assets/html5.js…
jq  -c -f ../scripts/local_governments_geojson.jq \
        --argfile govs ../lib/local_governments.json \
        ../lib/local_governments.geojson \
        > "../tmp/local_governments.geojson.json"
jq: error: round/0 is not defined at <top-level>, line 10:
        $gov + {threshold: [$gov.population * 0.01 | round, 5] | max}
jq: 1 compile error

**Comment by VenusKanami** [comment]
and do make is true

**Comment by moll** [comment]
Apart from hinting that the error message refers to `node-sass`, I don't know what the problem could be. As I said, try reinstalling `node-sass`. 

As for the `jq` error, you asked about that on Monday — https://github.com/rahvaalgatus/rahvaalgatus/issues/298. ;)
